/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `LHARLLMHTTPArchiveFormat`'s JSON-Schema
 * via the `definition` "CompositionCategory".
 */
export type CompositionCategory =
  | "system_prompt"
  | "tool_definitions"
  | "tool_results"
  | "tool_calls"
  | "assistant_text"
  | "user_text"
  | "thinking"
  | "system_injections"
  | "images"
  | "cache_markers"
  | "other";

/**
 * JSON Schema for the LHAR format. What HAR is for web traffic, but for LLM API calls.
 */
export interface LHARLLMHTTPArchiveFormat {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `LHARLLMHTTPArchiveFormat`'s JSON-Schema
 * via the `definition` "CompositionEntry".
 */
export interface CompositionEntry {
  category: CompositionCategory;
  tokens: number;
  pct: number;
  count: number;
}
/**
 * This interface was referenced by `LHARLLMHTTPArchiveFormat`'s JSON-Schema
 * via the `definition` "Timings".
 */
export interface Timings {
  send_ms: number;
  wait_ms: number;
  receive_ms: number;
  total_ms: number;
  tokens_per_second: number | null;
}
/**
 * This interface was referenced by `LHARLLMHTTPArchiveFormat`'s JSON-Schema
 * via the `definition` "LharSessionLine".
 */
export interface LharSessionLine {
  type: "session";
  trace_id: string;
  started_at: string;
  tool: string;
  model: string;
}
/**
 * This interface was referenced by `LHARLLMHTTPArchiveFormat`'s JSON-Schema
 * via the `definition` "LharRecord".
 */
export interface LharRecord {
  type: "entry";
  id: string;
  trace_id: string;
  span_id: string;
  parent_span_id: string | null;
  timestamp: string;
  sequence: number;
  source: {
    tool: string;
    tool_version: string | null;
    agent_role: string;
    collector: string;
    collector_version: string;
  };
  gen_ai: {
    system: string;
    request: {
      model: string;
      max_tokens: number | null;
      temperature: number | null;
      top_p: number | null;
      stop_sequences: string[];
    };
    response: {
      model: string | null;
      finish_reasons: string[];
    };
    usage: {
      input_tokens: number;
      output_tokens: number;
      total_tokens: number;
    };
  };
  usage_ext: {
    cache_read_tokens: number;
    cache_write_tokens: number;
    cost_usd: number | null;
  };
  http: {
    method: string;
    url: string | null;
    status_code: number | null;
    api_format: string;
    stream: boolean;
    request_headers: {
      [k: string]: string;
    };
    response_headers: {
      [k: string]: string;
    };
  };
  timings: Timings | null;
  transfer: {
    request_bytes: number;
    response_bytes: number;
    compressed: boolean;
  };
  context_lens: {
    window_size: number;
    utilization: number;
    system_tokens: number;
    tools_tokens: number;
    messages_tokens: number;
    composition: CompositionEntry[];
    growth: {
      tokens_added_this_turn: number | null;
      cumulative_tokens: number;
      compaction_detected: boolean;
    };
  };
  raw: {
    request_body: null;
    response_body: null;
  };
}
/**
 * This interface was referenced by `LHARLLMHTTPArchiveFormat`'s JSON-Schema
 * via the `definition` "LharJsonWrapper".
 */
export interface LharJsonWrapper {
  lhar: {
    version: string;
    creator: {
      name: string;
      version: string;
    };
    sessions: {
      trace_id: string;
      started_at: string;
      tool: string;
      model: string;
    }[];
    entries: LharRecord[];
  };
}
